=== Zettor/JavaWebDevelopment/Task4/src/main/resources/data/flowers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.ysenko.by/flowers"
        xmlns:tns="http://www.ysenko.by/flowers"
        elementFormDefault="qualified">


    <element name="flower" type="tns:Flower" abstract="true"></element>
    <element name="blossom" type="tns:Blossom" substitutionGroup="tns:flower"></element>
    <element name="cactus" type="tns:Сactus" substitutionGroup="tns:flower"></element>
    <element name="liana" type="tns:Liana" substitutionGroup="tns:flower"></element>
    <element name="flowers">
        <complexType>
            <sequence>
                <element ref="tns:flower" minOccurs="16" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="visual_parameters">
        <sequence>
            <element name="stem_color">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="Green"/>
                        <enumeration value="Orange"/>
                        <enumeration value="Pink"/>
                        <enumeration value="Brown"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="size" type="float"/>
        </sequence>
    </complexType>
    <complexType name="blossom_visual_parameters">
        <complexContent>
            <extension base="tns:visual_parameters">
                <sequence>
                    <element name="leaf_color">
                        <simpleType>
                            <restriction base="string">
                                <enumeration value="Green"/>
                                <enumeration value="Burgundy"/>
                                <enumeration value="Pink"/>
                                <enumeration value="Yellow"/>
                            </restriction>
                        </simpleType>
                    </element>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="liana_visual_parameters">
            <complexContent>
                <extension base="tns:visual_parameters">
                    <sequence>
                        <element name="leaf_type">
                            <simpleType>
                                <restriction base="string">
                                    <enumeration value="Tendrils"/>
                                    <enumeration value="Ivy"/>
                                    <enumeration value="Roots"/>
                                    <enumeration value="Stalks"/>
                                </restriction>
                            </simpleType>
                        </element>
                    </sequence>
                </extension>
            </complexContent>

    </complexType>

    <complexType name="growing_tips">
        <sequence>
            <element name="temperature" type="positiveInteger"/>
            <element name="lighting" type="boolean"/>
            <element name="watering" type="float"/>
        </sequence>
    </complexType>


    <complexType name="Flower">

        <sequence>
            <element name="name" type="string"/>
            <element name="soil">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="Podzolic"/>
                        <enumeration value="Ground"/>
                        <enumeration value="Sod-podzolic"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="growing_tips" type="tns:growing_tips"/>
            <element name="multiplying">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="Cuttings"/>
                        <enumeration value="Spores"/>
                        <enumeration value="Seeds"/>
                        <enumeration value="Tubers"/>
                        <enumeration value="Budding"/>
                    </restriction>
                </simpleType>
            </element>
        </sequence>
        <attribute name="id" use="required">
            <simpleType>
                <restriction base="ID">
                    <pattern value="(id)[\d]+"/>
                </restriction>
            </simpleType>
        </attribute>
        <attribute name="origin" use="optional" default="USA">
            <simpleType>
                <restriction base="string">
                    <enumeration value="Chine"/>
                    <enumeration value="USA"/>
                    <enumeration value="Central America"/>
                    <enumeration value="Greece"/>
                    <enumeration value="Spain"/>
                    <enumeration value="India"/>
                    <enumeration value="Brazil"/>
                    <enumeration value="Belarus"/>
                    <enumeration value="Bolivia"/>
                    <enumeration value="Argentina"/>
                </restriction>
            </simpleType>
        </attribute>
        <!--<attribute name="lifetime" use="optional" type="positiveInteger"/>-->
    </complexType>

    <complexType name="Blossom">
        <complexContent>
            <extension base="tns:Flower">
                <sequence>
                    <element name="visual_parameters" type="tns:blossom_visual_parameters"></element>
                    <element name="fruits" type="boolean"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Сactus">
        <complexContent>
            <extension base="tns:Flower">
                <sequence>
                    <element name="visual_parameters" type="tns:visual_parameters"/>
                    <element name="subfamily">
                        <simpleType>
                            <restriction base="string">
                                <enumeration value="Pereskioideae"/>
                                <enumeration value="Maihuenioideae"/>
                                <enumeration value="Opuntioideae"/>
                                <enumeration value="Cactoideae"/>
                            </restriction>
                        </simpleType>
                    </element>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Liana">
        <complexContent>
            <extension base="tns:Flower">
                <sequence>
                   <element name="visual_parameters" type="tns:liana_visual_parameters"/>
                    <element name="type">
                        <simpleType>
                            <restriction base="string">
                                <enumeration value="Woody"/>
                                <enumeration value="Herbaceous"/>
                            </restriction>
                        </simpleType>
                    </element>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
</schema>

=== Zettor/JavaWebDevelopment/Task4/web/WEB-INF/classes/data/flowers.xml
<?xml version="1.0" encoding="UTF-8"?>
<flowers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.ysenko.by/flowers"
         xsi:schemaLocation="http://www.ysenko.by/flowers flowers.xsd">
    <blossom id="id1" origin="Chine">
        <name>"Rose"</name>
        <soil>Podzolic</soil>
        <growing_tips>
            <temperature>5</temperature>
            <lighting>true</lighting>
            <watering>150.0</watering>
        </growing_tips>
        <multiplying>Cuttings</multiplying>
        <visual_parameters>
            <stem_color>Green</stem_color>
            <size>65.0</size>
            <leaf_color>Green</leaf_color>
        </visual_parameters>
        <fruits>false</fruits>
    </blossom>
    <blossom id="id2">
        <name>"Amazonian Lily"</name>
        <soil>Ground</soil>
        <growing_tips>
            <temperature>19</temperature>
            <lighting>false</lighting>
            <watering>105.0</watering>
        </growing_tips>
        <multiplying>Seeds</multiplying>
        <visual_parameters>
            <stem_color>Green</stem_color>
            <size>70.0</size>
            <leaf_color>Green</leaf_color>
        </visual_parameters>
        <fruits>false</fruits>
    </blossom>
    <liana id="id3"  origin="Greece">
        <name>"Clematis"</name>
        <soil>Podzolic</soil>
        <growing_tips>
            <temperature>23</temperature>
            <lighting>true</lighting>
            <watering>400.0</watering>
        </growing_tips>
        <multiplying>Cuttings</multiplying>
        <visual_parameters>
            <stem_color>Green</stem_color>
            <size>100.0</size>
            <leaf_type>Tendrils</leaf_type>
        </visual_parameters>
        <type>Herbaceous</type>
    </liana>
    <liana id="id4" origin="Central America">
        <name>"Passionflower"</name>
        <soil>Sod-podzolic</soil>
        <growing_tips>
            <temperature>13</temperature>
            <lighting>true</lighting>
            <watering>500.0</watering>
        </growing_tips>
        <multiplying>Cuttings</multiplying>
        <visual_parameters>
            <stem_color>Green</stem_color>
            <size>1000.0</size>
            <leaf_type>Roots</leaf_type>
        </visual_parameters>
        <type>Woody</type>

    </liana>
    <liana id="id5" origin="Chine">
        <name>"Campsis"</name>
        <soil>Ground</soil>
        <growing_tips>
            <temperature>20</temperature>
            <lighting>true</lighting>
            <watering>600.0</watering>
        </growing_tips>
        <multiplying>Seeds</multiplying>
        <visual_parameters>
            <stem_color>Green</stem_color>
            <size>1000.0</size>
            <leaf_type>Stalks</leaf_type>
        </visual_parameters>
        <type>Woody</type>
    </liana>
    <blossom id="id6">
        <name>Lilac</name>
        <soil>Podzolic</soil>
        <growing_tips>
            <temperature>25</temperature>
            <lighting>true</lighting>
            <watering>100.0</watering>
        </growing_tips>
        <multiplying>Seeds</multiplying>
        <visual_parameters>
            <stem_color>Green</stem_color>
            <size>20.0</size>
            <leaf_color>Green</leaf_color>
        </visual_parameters>
        <fruits>false</fruits>
    </blossom>
    <blossom id="id7" origin="Spain">
        <name>"Cyclamen"</name>
        <soil>Ground</soil>
        <growing_tips>
            <temperature>20</temperature>
            <lighting>false</lighting>
            <watering>200.0</watering>
        </growing_tips>
        <multiplying>Tubers</multiplying>
        <visual_parameters>
            <stem_color>Green</stem_color>
            <size>20.0</size>
            <leaf_color>Green</leaf_color>
        </visual_parameters>
        <fruits>true</fruits>

    </blossom>
    <blossom id="id8" origin="Chine">
        <name>"Badan"</name>
        <soil>Ground</soil>
        <growing_tips>
            <temperature>18</temperature>
            <lighting>false</lighting>
            <watering>306.0</watering>
        </growing_tips>
        <multiplying>Seeds</multiplying>
        <visual_parameters>
            <stem_color>Pink</stem_color>
            <size>70.0</size>
            <leaf_color>Green</leaf_color>
        </visual_parameters>
<fruits>true</fruits>
    </blossom>
    <blossom id="id9" origin="India">
        <name>"Ficus Benjamin"</name>
        <soil>Ground</soil>
        <growing_tips>
            <temperature>20</temperature>
            <lighting>true</lighting>
            <watering>300.0</watering>
        </growing_tips>
        <multiplying>Cuttings</multiplying>
        <visual_parameters>
            <stem_color>Brown</stem_color>
            <size>150.0</size>
            <leaf_color>Green</leaf_color>
        </visual_parameters>
        <fruits>false</fruits>
    </blossom>
    <blossom id="id10" origin="Brazil">
        <name>"Begonia"</name>
        <soil>Ground</soil>
        <growing_tips>
            <temperature>20</temperature>
            <lighting>true</lighting>
            <watering>350.0</watering>
        </growing_tips>
        <multiplying>Cuttings</multiplying>
        <visual_parameters>
            <stem_color>Green</stem_color>
            <size>30.0</size>
            <leaf_color>Burgundy</leaf_color>
        </visual_parameters>
        <fruits>false</fruits>
    </blossom>
    <blossom id="id11" origin="Belarus">
        <name>"Blooming Sally"</name>
        <soil>Podzolic</soil>
        <growing_tips>
            <temperature>20</temperature>
            <lighting>false</lighting>
            <watering>200.0</watering>
        </growing_tips>
        <multiplying>Seeds</multiplying>
        <visual_parameters>
            <stem_color>Green</stem_color>
            <size>150.0</size>
            <leaf_color>Green</leaf_color>
        </visual_parameters>
        <fruits>true</fruits>
    </blossom>
    <cactus id="id12" origin="Bolivia">
        <name>"Echinopsis"</name>
        <soil>Sod-podzolic</soil>
        <growing_tips>
            <temperature>20</temperature>
            <lighting>false</lighting>
            <watering>50.0</watering>
        </growing_tips>
        <multiplying>Budding</multiplying>
        <visual_parameters>
            <stem_color>Green</stem_color>
            <size>20.0</size>
        </visual_parameters>
        <subfamily>Pereskioideae</subfamily>
    </cactus>
    <cactus id="id13" origin="Argentina">
        <name>"Rebucius"</name>
        <soil>Sod-podzolic</soil>
        <growing_tips>
            <temperature>20</temperature>
            <lighting>false</lighting>
            <watering>50.0</watering>
        </growing_tips>
        <multiplying>Budding</multiplying>
        <visual_parameters>
            <stem_color>Green</stem_color>
            <size>10.0</size>
        </visual_parameters>
        <subfamily>Opuntioideae</subfamily>
    </cactus>
    <blossom id="id14" origin="Brazil">
        <name>"Stromantha"</name>
        <soil>Ground</soil>
        <growing_tips>
            <temperature>22</temperature>
            <lighting>false</lighting>
            <watering>200.0</watering>
        </growing_tips>
        <multiplying>Cuttings</multiplying>
        <visual_parameters>
            <stem_color>Orange</stem_color>
            <size>50.0</size>
            <leaf_color>Green</leaf_color>
        </visual_parameters>
        <fruits>false</fruits>
    </blossom>
    <blossom id="id15" origin="Central America">
        <name>"Agave"</name>
        <soil>Ground</soil>
        <growing_tips>
            <temperature>25</temperature>
            <lighting>false</lighting>
            <watering>100.0</watering>
        </growing_tips>
        <multiplying>Cuttings</multiplying>
        <visual_parameters>
            <stem_color>Green</stem_color>
            <size>150.0</size>
            <leaf_color>Green</leaf_color>
        </visual_parameters>
        <fruits>false</fruits>

    </blossom>
    <blossom id="id16" origin="India">
        <name>"Azalea"</name>
        <soil>Ground</soil>
        <growing_tips>
            <temperature>12</temperature>
            <lighting>true</lighting>
            <watering>200.0</watering>
        </growing_tips>
        <multiplying>Cuttings</multiplying>
        <visual_parameters>
            <stem_color>Green</stem_color>
            <size>210.0</size>
            <leaf_color>Green</leaf_color>
        </visual_parameters>
        <fruits>true</fruits>
    </blossom>
</flowers>
